           
diagram_fact(as, cell_10, "geometry").
diagram_fact(as, cell_11, "geometry").
diagram_fact(as, cell_12, "geometry").
diagram_fact(as, cell_13, "geometry").
diagram_fact(as, cell_14, "geometry").
diagram_fact(as, cell_15, "geometry").
diagram_fact(as, cell_16, "geometry").
diagram_fact(as, cell_17, "geometry").
diagram_fact(as, cell_18, "geometry").
diagram_fact(as, cell_19, "geometry").
diagram_fact(as, cell_20, "geometry").
diagram_fact(as, cell_21, "geometry").
diagram_fact(as, cell_22, "geometry").
diagram_fact(as, cell_23, "geometry").
diagram_fact(as, cell_24, "geometry").
diagram_fact(as, cell_25, "geometry").
diagram_fact(as, cell_26, "geometry").
diagram_fact(as, cell_27, "geometry").
diagram_fact(as, cell_28, "geometry").
diagram_fact(as, cell_29, "geometry").
diagram_fact(as, cell_30, "geometry").
diagram_fact(as, cell_31, "geometry").
diagram_fact(as, cell_32, "geometry").
diagram_fact(as, cell_33, "geometry").
diagram_fact(as, cell_34, "geometry").
diagram_fact(as, cell_35, "geometry").
diagram_fact(as, cell_36, "geometry").
diagram_fact(as, cell_37, "geometry").
diagram_fact(as, cell_38, "geometry").
diagram_fact(as, cell_39, "geometry").
diagram_fact(as, cell_40, "geometry").
diagram_fact(as, cell_41, "geometry").
diagram_fact(as, cell_42, "geometry").
diagram_fact(as, cell_43, "geometry").
diagram_fact(as, cell_44, "geometry").
diagram_fact(as, cell_45, "geometry").
diagram_fact(as, cell_46, "geometry").
diagram_fact(as, cell_47, "geometry").
diagram_fact(as, cell_48, "geometry").
diagram_fact(as, cell_49, "geometry").
diagram_fact(as, cell_50, "geometry").
diagram_fact(as, cell_51, "geometry").
diagram_fact(as, cell_52, "geometry").
diagram_fact(as, cell_53, "geometry").
diagram_fact(as, cell_54, "geometry").
diagram_fact(as, cell_55, "geometry").
diagram_fact(as, cell_56, "geometry").
diagram_fact(as, cell_57, "geometry").
diagram_fact(as, cell_58, "geometry").
diagram_fact(as, cell_59, "geometry").
diagram_fact(as, cell_6, "geometry").
diagram_fact(as, cell_60, "geometry").
diagram_fact(as, cell_61, "geometry").
diagram_fact(as, cell_62, "geometry").
diagram_fact(as, cell_63, "geometry").
diagram_fact(as, cell_64, "geometry").
diagram_fact(as, cell_7, "geometry").
diagram_fact(as, cell_8, "geometry").
diagram_fact(as, cell_9, "geometry").
diagram_fact(aspect, cell_10, "fixed").
diagram_fact(aspect, cell_14, "fixed").
diagram_fact(aspect, cell_16, "fixed").
diagram_fact(aspect, cell_17, "fixed").
diagram_fact(aspect, cell_18, "fixed").
diagram_fact(aspect, cell_21, "fixed").
diagram_fact(aspect, cell_22, "fixed").
diagram_fact(aspect, cell_24, "fixed").
diagram_fact(aspect, cell_26, "fixed").
diagram_fact(aspect, cell_28, "fixed").
diagram_fact(aspect, cell_33, "fixed").
diagram_fact(aspect, cell_34, "fixed").
diagram_fact(aspect, cell_38, "fixed").
diagram_fact(aspect, cell_39, "fixed").
diagram_fact(aspect, cell_43, "fixed").
diagram_fact(aspect, cell_44, "fixed").
diagram_fact(aspect, cell_46, "fixed").
diagram_fact(aspect, cell_48, "fixed").
diagram_fact(aspect, cell_49, "fixed").
diagram_fact(aspect, cell_51, "fixed").
diagram_fact(aspect, cell_54, "fixed").
diagram_fact(aspect, cell_55, "fixed").
diagram_fact(aspect, cell_57, "fixed").
diagram_fact(aspect, cell_59, "fixed").
diagram_fact(aspect, cell_60, "fixed").
diagram_fact(aspect, cell_62, "fixed").
diagram_fact(aspect, cell_63, "fixed").
diagram_fact(aspect, cell_8, "fixed").
diagram_fact(cell, cell_10, "").
diagram_fact(cell, cell_11, "").
diagram_fact(cell, cell_12, "").
diagram_fact(cell, cell_13, "").
diagram_fact(cell, cell_14, "").
diagram_fact(cell, cell_15, "").
diagram_fact(cell, cell_16, "").
diagram_fact(cell, cell_17, "").
diagram_fact(cell, cell_18, "").
diagram_fact(cell, cell_19, "").
diagram_fact(cell, cell_20, "").
diagram_fact(cell, cell_21, "").
diagram_fact(cell, cell_22, "").
diagram_fact(cell, cell_23, "").
diagram_fact(cell, cell_24, "").
diagram_fact(cell, cell_25, "").
diagram_fact(cell, cell_26, "").
diagram_fact(cell, cell_27, "").
diagram_fact(cell, cell_28, "").
diagram_fact(cell, cell_29, "").
diagram_fact(cell, cell_30, "").
diagram_fact(cell, cell_31, "").
diagram_fact(cell, cell_32, "").
diagram_fact(cell, cell_33, "").
diagram_fact(cell, cell_34, "").
diagram_fact(cell, cell_35, "").
diagram_fact(cell, cell_36, "").
diagram_fact(cell, cell_37, "").
diagram_fact(cell, cell_38, "").
diagram_fact(cell, cell_39, "").
diagram_fact(cell, cell_4, "").
diagram_fact(cell, cell_40, "").
diagram_fact(cell, cell_41, "").
diagram_fact(cell, cell_42, "").
diagram_fact(cell, cell_43, "").
diagram_fact(cell, cell_44, "").
diagram_fact(cell, cell_45, "").
diagram_fact(cell, cell_46, "").
diagram_fact(cell, cell_47, "").
diagram_fact(cell, cell_48, "").
diagram_fact(cell, cell_49, "").
diagram_fact(cell, cell_5, "").
diagram_fact(cell, cell_50, "").
diagram_fact(cell, cell_51, "").
diagram_fact(cell, cell_52, "").
diagram_fact(cell, cell_53, "").
diagram_fact(cell, cell_54, "").
diagram_fact(cell, cell_55, "").
diagram_fact(cell, cell_56, "").
diagram_fact(cell, cell_57, "").
diagram_fact(cell, cell_58, "").
diagram_fact(cell, cell_59, "").
diagram_fact(cell, cell_6, "").
diagram_fact(cell, cell_60, "").
diagram_fact(cell, cell_61, "").
diagram_fact(cell, cell_62, "").
diagram_fact(cell, cell_63, "").
diagram_fact(cell, cell_64, "").
diagram_fact(cell, cell_7, "").
diagram_fact(cell, cell_8, "").
diagram_fact(cell, cell_9, "").
diagram_fact(diagram, diagram_1, "").
diagram_fact(edge, cell_12, 1).
diagram_fact(edge, cell_13, 1).
diagram_fact(edge, cell_20, 1).
diagram_fact(edge, cell_23, 1).
diagram_fact(edge, cell_25, 1).
diagram_fact(edge, cell_27, 1).
diagram_fact(edge, cell_32, 1).
diagram_fact(edge, cell_37, 1).
diagram_fact(edge, cell_42, 1).
diagram_fact(edge, cell_53, 1).
diagram_fact(edge, cell_56, 1).
diagram_fact(edge, cell_9, 1).
diagram_fact(edgeStyle, cell_12, "orthogonalEdgeStyle").
diagram_fact(edgeStyle, cell_13, "orthogonalEdgeStyle").
diagram_fact(edgeStyle, cell_20, "orthogonalEdgeStyle").
diagram_fact(edgeStyle, cell_23, "orthogonalEdgeStyle").
diagram_fact(edgeStyle, cell_25, "orthogonalEdgeStyle").
diagram_fact(edgeStyle, cell_27, "orthogonalEdgeStyle").
diagram_fact(edgeStyle, cell_32, "orthogonalEdgeStyle").
diagram_fact(edgeStyle, cell_37, "orthogonalEdgeStyle").
diagram_fact(edgeStyle, cell_42, "orthogonalEdgeStyle").
diagram_fact(edgeStyle, cell_53, "orthogonalEdgeStyle").
diagram_fact(edgeStyle, cell_56, "orthogonalEdgeStyle").
diagram_fact(edgeStyle, cell_9, "orthogonalEdgeStyle").
diagram_fact(entryDx, cell_12, 0).
diagram_fact(entryDx, cell_13, 0).
diagram_fact(entryDx, cell_25, 0).
diagram_fact(entryDx, cell_27, 0).
diagram_fact(entryDx, cell_32, 0).
diagram_fact(entryDx, cell_37, 0).
diagram_fact(entryDx, cell_42, 0).
diagram_fact(entryDx, cell_53, 0).
diagram_fact(entryDx, cell_56, 0).
diagram_fact(entryDy, cell_12, 0).
diagram_fact(entryDy, cell_13, 0).
diagram_fact(entryDy, cell_25, 0).
diagram_fact(entryDy, cell_27, 0).
diagram_fact(entryDy, cell_32, 0).
diagram_fact(entryDy, cell_37, 0).
diagram_fact(entryDy, cell_42, 0).
diagram_fact(entryDy, cell_53, 0).
diagram_fact(entryDy, cell_56, 0).
diagram_fact(entryX, cell_12, 0).
diagram_fact(entryX, cell_13, 0).
diagram_fact(entryX, cell_25, 0).
diagram_fact(entryX, cell_27, 0).
diagram_fact(entryX, cell_32, 0).
diagram_fact(entryX, cell_37, 0).
diagram_fact(entryX, cell_42, 0).
diagram_fact(entryX, cell_53, 0).
diagram_fact(entryX, cell_56, 0).
diagram_fact(entryY, cell_12, 0.5).
diagram_fact(entryY, cell_13, 0.5).
diagram_fact(entryY, cell_25, 0.5).
diagram_fact(entryY, cell_27, 0.5).
diagram_fact(entryY, cell_32, 0.5).
diagram_fact(entryY, cell_37, 0).
diagram_fact(entryY, cell_42, 0.5).
diagram_fact(entryY, cell_53, 1).
diagram_fact(entryY, cell_56, 0.5).
diagram_fact(exitDx, cell_12, 0).
diagram_fact(exitDx, cell_13, 0).
diagram_fact(exitDx, cell_20, 0).
diagram_fact(exitDx, cell_23, 0).
diagram_fact(exitDx, cell_25, 0).
diagram_fact(exitDx, cell_27, 0).
diagram_fact(exitDx, cell_32, 0).
diagram_fact(exitDx, cell_37, 0).
diagram_fact(exitDx, cell_42, 0).
diagram_fact(exitDx, cell_53, 0).
diagram_fact(exitDx, cell_56, 0).
diagram_fact(exitDx, cell_9, 0).
diagram_fact(exitDy, cell_12, 0).
diagram_fact(exitDy, cell_13, 0).
diagram_fact(exitDy, cell_20, 0).
diagram_fact(exitDy, cell_23, 0).
diagram_fact(exitDy, cell_25, 0).
diagram_fact(exitDy, cell_27, 0).
diagram_fact(exitDy, cell_32, 0).
diagram_fact(exitDy, cell_37, 0).
diagram_fact(exitDy, cell_42, 0).
diagram_fact(exitDy, cell_53, 0).
diagram_fact(exitDy, cell_56, 0).
diagram_fact(exitDy, cell_9, 0).
diagram_fact(exitX, cell_12, 1).
diagram_fact(exitX, cell_13, 1).
diagram_fact(exitX, cell_20, 1).
diagram_fact(exitX, cell_23, 1).
diagram_fact(exitX, cell_25, 0.5).
diagram_fact(exitX, cell_27, 0.5).
diagram_fact(exitX, cell_32, 1).
diagram_fact(exitX, cell_37, 1).
diagram_fact(exitX, cell_42, 1).
diagram_fact(exitX, cell_53, 1).
diagram_fact(exitX, cell_56, 1).
diagram_fact(exitX, cell_9, 1).
diagram_fact(exitY, cell_12, 0.5).
diagram_fact(exitY, cell_13, 1).
diagram_fact(exitY, cell_20, 0.5).
diagram_fact(exitY, cell_23, 0.5).
diagram_fact(exitY, cell_25, 1).
diagram_fact(exitY, cell_27, 1).
diagram_fact(exitY, cell_32, 0.5).
diagram_fact(exitY, cell_37, 0.5).
diagram_fact(exitY, cell_42, 0.5).
diagram_fact(exitY, cell_53, 0.5).
diagram_fact(exitY, cell_56, 0.5).
diagram_fact(exitY, cell_9, 0.5).
diagram_fact(fillColor, cell_10, "#d5e8d4").
diagram_fact(fillColor, cell_11, "#dae8fc").
diagram_fact(fillColor, cell_14, "#fff2cc").
diagram_fact(fillColor, cell_15, "#dae8fc").
diagram_fact(fillColor, cell_16, "#fff2cc").
diagram_fact(fillColor, cell_17, "#d5e8d4").
diagram_fact(fillColor, cell_18, "#fff2cc").
diagram_fact(fillColor, cell_19, "#dae8fc").
diagram_fact(fillColor, cell_21, "#fff2cc").
diagram_fact(fillColor, cell_22, "#d5e8d4").
diagram_fact(fillColor, cell_24, "#fff2cc").
diagram_fact(fillColor, cell_26, "#fff2cc").
diagram_fact(fillColor, cell_28, "#fff2cc").
diagram_fact(fillColor, cell_29, "#f8cecc").
diagram_fact(fillColor, cell_30, "#f8cecc").
diagram_fact(fillColor, cell_31, "#dae8fc").
diagram_fact(fillColor, cell_33, "#fff2cc").
diagram_fact(fillColor, cell_34, "#d5e8d4").
diagram_fact(fillColor, cell_35, "#f8cecc").
diagram_fact(fillColor, cell_36, "#dae8fc").
diagram_fact(fillColor, cell_38, "#fff2cc").
diagram_fact(fillColor, cell_39, "#d5e8d4").
diagram_fact(fillColor, cell_40, "#f8cecc").
diagram_fact(fillColor, cell_41, "#dae8fc").
diagram_fact(fillColor, cell_43, "#fff2cc").
diagram_fact(fillColor, cell_44, "#d5e8d4").
diagram_fact(fillColor, cell_45, "#f8cecc").
diagram_fact(fillColor, cell_46, "#d5e8d4").
diagram_fact(fillColor, cell_47, "#dae8fc").
diagram_fact(fillColor, cell_48, "#fff2cc").
diagram_fact(fillColor, cell_49, "#d5e8d4").
diagram_fact(fillColor, cell_50, "#f8cecc").
diagram_fact(fillColor, cell_51, "#fff2cc").
diagram_fact(fillColor, cell_52, "#dae8fc").
diagram_fact(fillColor, cell_54, "#fff2cc").
diagram_fact(fillColor, cell_55, "#d5e8d4").
diagram_fact(fillColor, cell_57, "#fff2cc").
diagram_fact(fillColor, cell_58, "#dae8fc").
diagram_fact(fillColor, cell_59, "#fff2cc").
diagram_fact(fillColor, cell_6, "#f5f5f5").
diagram_fact(fillColor, cell_60, "#d5e8d4").
diagram_fact(fillColor, cell_61, "#f8cecc").
diagram_fact(fillColor, cell_62, "#d5e8d4").
diagram_fact(fillColor, cell_63, "#d5e8d4").
diagram_fact(fillColor, cell_64, "#f8cecc").
diagram_fact(fillColor, cell_7, "#f5f5f5").
diagram_fact(fillColor, cell_8, "#fff2cc").
diagram_fact(gradientColor, cell_11, "#7ea6e0").
diagram_fact(gradientColor, cell_15, "#7ea6e0").
diagram_fact(gradientColor, cell_19, "#7ea6e0").
diagram_fact(gradientColor, cell_31, "#7ea6e0").
diagram_fact(gradientColor, cell_36, "#7ea6e0").
diagram_fact(gradientColor, cell_41, "#7ea6e0").
diagram_fact(gradientColor, cell_47, "#7ea6e0").
diagram_fact(gradientColor, cell_52, "#7ea6e0").
diagram_fact(gradientColor, cell_58, "#7ea6e0").
diagram_fact(gradientColor, cell_6, "#b3b3b3").
diagram_fact(gradientColor, cell_7, "#b3b3b3").
diagram_fact(gradientDirection, cell_6, "north").
diagram_fact(height, cell_10, 40).
diagram_fact(height, cell_11, 110).
diagram_fact(height, cell_14, 40).
diagram_fact(height, cell_15, 120).
diagram_fact(height, cell_16, 40).
diagram_fact(height, cell_17, 40).
diagram_fact(height, cell_18, 40).
diagram_fact(height, cell_19, 150).
diagram_fact(height, cell_21, 40).
diagram_fact(height, cell_22, 40).
diagram_fact(height, cell_24, 40).
diagram_fact(height, cell_26, 40).
diagram_fact(height, cell_28, 40).
diagram_fact(height, cell_29, 40).
diagram_fact(height, cell_30, 60).
diagram_fact(height, cell_31, 140).
diagram_fact(height, cell_33, 40).
diagram_fact(height, cell_34, 40).
diagram_fact(height, cell_35, 85).
diagram_fact(height, cell_36, 120).
diagram_fact(height, cell_38, 40).
diagram_fact(height, cell_39, 40).
diagram_fact(height, cell_40, 60).
diagram_fact(height, cell_41, 140).
diagram_fact(height, cell_43, 40).
diagram_fact(height, cell_44, 40).
diagram_fact(height, cell_45, 85).
diagram_fact(height, cell_46, 40).
diagram_fact(height, cell_47, 180).
diagram_fact(height, cell_48, 40).
diagram_fact(height, cell_49, 40).
diagram_fact(height, cell_50, 85).
diagram_fact(height, cell_51, 40).
diagram_fact(height, cell_52, 180).
diagram_fact(height, cell_54, 40).
diagram_fact(height, cell_55, 40).
diagram_fact(height, cell_57, 40).
diagram_fact(height, cell_58, 220).
diagram_fact(height, cell_59, 40).
diagram_fact(height, cell_6, 1060).
diagram_fact(height, cell_60, 40).
diagram_fact(height, cell_61, 60).
diagram_fact(height, cell_62, 40).
diagram_fact(height, cell_63, 40).
diagram_fact(height, cell_64, 85).
diagram_fact(height, cell_7, 285).
diagram_fact(height, cell_8, 40).
diagram_fact(horizontal, cell_6, 1).
diagram_fact(horizontal, cell_7, 1).
diagram_fact(html, cell_10, 1).
diagram_fact(html, cell_11, 1).
diagram_fact(html, cell_12, 1).
diagram_fact(html, cell_13, 1).
diagram_fact(html, cell_14, 1).
diagram_fact(html, cell_15, 1).
diagram_fact(html, cell_16, 1).
diagram_fact(html, cell_17, 1).
diagram_fact(html, cell_18, 1).
diagram_fact(html, cell_19, 1).
diagram_fact(html, cell_20, 1).
diagram_fact(html, cell_21, 1).
diagram_fact(html, cell_22, 1).
diagram_fact(html, cell_23, 1).
diagram_fact(html, cell_24, 1).
diagram_fact(html, cell_25, 1).
diagram_fact(html, cell_26, 1).
diagram_fact(html, cell_27, 1).
diagram_fact(html, cell_28, 1).
diagram_fact(html, cell_29, 1).
diagram_fact(html, cell_30, 1).
diagram_fact(html, cell_31, 1).
diagram_fact(html, cell_32, 1).
diagram_fact(html, cell_33, 1).
diagram_fact(html, cell_34, 1).
diagram_fact(html, cell_35, 1).
diagram_fact(html, cell_36, 1).
diagram_fact(html, cell_37, 1).
diagram_fact(html, cell_38, 1).
diagram_fact(html, cell_39, 1).
diagram_fact(html, cell_40, 1).
diagram_fact(html, cell_41, 1).
diagram_fact(html, cell_42, 1).
diagram_fact(html, cell_43, 1).
diagram_fact(html, cell_44, 1).
diagram_fact(html, cell_45, 1).
diagram_fact(html, cell_46, 1).
diagram_fact(html, cell_47, 1).
diagram_fact(html, cell_48, 1).
diagram_fact(html, cell_49, 1).
diagram_fact(html, cell_50, 1).
diagram_fact(html, cell_51, 1).
diagram_fact(html, cell_52, 1).
diagram_fact(html, cell_53, 1).
diagram_fact(html, cell_54, 1).
diagram_fact(html, cell_55, 1).
diagram_fact(html, cell_56, 1).
diagram_fact(html, cell_57, 1).
diagram_fact(html, cell_58, 1).
diagram_fact(html, cell_59, 1).
diagram_fact(html, cell_6, 1).
diagram_fact(html, cell_60, 1).
diagram_fact(html, cell_61, 1).
diagram_fact(html, cell_62, 1).
diagram_fact(html, cell_63, 1).
diagram_fact(html, cell_64, 1).
diagram_fact(html, cell_7, 1).
diagram_fact(html, cell_8, 1).
diagram_fact(html, cell_9, 1).
diagram_fact(jettySize, cell_12, "auto").
diagram_fact(jettySize, cell_13, "auto").
diagram_fact(jettySize, cell_20, "auto").
diagram_fact(jettySize, cell_23, "auto").
diagram_fact(jettySize, cell_25, "auto").
diagram_fact(jettySize, cell_27, "auto").
diagram_fact(jettySize, cell_32, "auto").
diagram_fact(jettySize, cell_37, "auto").
diagram_fact(jettySize, cell_42, "auto").
diagram_fact(jettySize, cell_53, "auto").
diagram_fact(jettySize, cell_56, "auto").
diagram_fact(jettySize, cell_9, "auto").
diagram_fact(kind, cell_10, "ellipse").
diagram_fact(kind, cell_14, "ellipse").
diagram_fact(kind, cell_16, "ellipse").
diagram_fact(kind, cell_17, "ellipse").
diagram_fact(kind, cell_18, "ellipse").
diagram_fact(kind, cell_21, "ellipse").
diagram_fact(kind, cell_22, "ellipse").
diagram_fact(kind, cell_24, "ellipse").
diagram_fact(kind, cell_26, "ellipse").
diagram_fact(kind, cell_28, "ellipse").
diagram_fact(kind, cell_33, "ellipse").
diagram_fact(kind, cell_34, "ellipse").
diagram_fact(kind, cell_38, "ellipse").
diagram_fact(kind, cell_39, "ellipse").
diagram_fact(kind, cell_43, "ellipse").
diagram_fact(kind, cell_44, "ellipse").
diagram_fact(kind, cell_46, "ellipse").
diagram_fact(kind, cell_48, "ellipse").
diagram_fact(kind, cell_49, "ellipse").
diagram_fact(kind, cell_51, "ellipse").
diagram_fact(kind, cell_54, "ellipse").
diagram_fact(kind, cell_55, "ellipse").
diagram_fact(kind, cell_57, "ellipse").
diagram_fact(kind, cell_59, "ellipse").
diagram_fact(kind, cell_60, "ellipse").
diagram_fact(kind, cell_62, "ellipse").
diagram_fact(kind, cell_63, "ellipse").
diagram_fact(kind, cell_8, "ellipse").
diagram_fact(mxGraphModel, mxGraphModel_2, mxGraphModel_2).
diagram_fact(name, diagram_1, "testbench").
diagram_fact(orthogonalLoop, cell_12, 1).
diagram_fact(orthogonalLoop, cell_13, 1).
diagram_fact(orthogonalLoop, cell_20, 1).
diagram_fact(orthogonalLoop, cell_23, 1).
diagram_fact(orthogonalLoop, cell_25, 1).
diagram_fact(orthogonalLoop, cell_27, 1).
diagram_fact(orthogonalLoop, cell_32, 1).
diagram_fact(orthogonalLoop, cell_37, 1).
diagram_fact(orthogonalLoop, cell_42, 1).
diagram_fact(orthogonalLoop, cell_53, 1).
diagram_fact(orthogonalLoop, cell_56, 1).
diagram_fact(orthogonalLoop, cell_9, 1).
diagram_fact(parent, cell_10, id_1).
diagram_fact(parent, cell_11, id_1).
diagram_fact(parent, cell_12, id_1).
diagram_fact(parent, cell_13, id_1).
diagram_fact(parent, cell_14, id_1).
diagram_fact(parent, cell_15, id_1).
diagram_fact(parent, cell_16, id_1).
diagram_fact(parent, cell_17, id_1).
diagram_fact(parent, cell_18, id_1).
diagram_fact(parent, cell_19, id_1).
diagram_fact(parent, cell_20, id_1).
diagram_fact(parent, cell_21, id_1).
diagram_fact(parent, cell_22, id_1).
diagram_fact(parent, cell_23, id_1).
diagram_fact(parent, cell_24, id_1).
diagram_fact(parent, cell_25, id_1).
diagram_fact(parent, cell_26, id_1).
diagram_fact(parent, cell_27, id_1).
diagram_fact(parent, cell_28, id_1).
diagram_fact(parent, cell_29, id_1).
diagram_fact(parent, cell_30, id_1).
diagram_fact(parent, cell_31, id_1).
diagram_fact(parent, cell_32, id_1).
diagram_fact(parent, cell_33, id_1).
diagram_fact(parent, cell_34, id_1).
diagram_fact(parent, cell_35, id_1).
diagram_fact(parent, cell_36, id_1).
diagram_fact(parent, cell_37, id_1).
diagram_fact(parent, cell_38, id_1).
diagram_fact(parent, cell_39, id_1).
diagram_fact(parent, cell_40, id_1).
diagram_fact(parent, cell_41, id_1).
diagram_fact(parent, cell_42, id_1).
diagram_fact(parent, cell_43, id_1).
diagram_fact(parent, cell_44, id_1).
diagram_fact(parent, cell_45, id_1).
diagram_fact(parent, cell_46, id_1).
diagram_fact(parent, cell_47, id_1).
diagram_fact(parent, cell_48, id_1).
diagram_fact(parent, cell_49, id_1).
diagram_fact(parent, cell_5, id_0).
diagram_fact(parent, cell_50, id_1).
diagram_fact(parent, cell_51, id_1).
diagram_fact(parent, cell_52, id_1).
diagram_fact(parent, cell_53, id_1).
diagram_fact(parent, cell_54, id_1).
diagram_fact(parent, cell_55, id_1).
diagram_fact(parent, cell_56, id_1).
diagram_fact(parent, cell_57, id_1).
diagram_fact(parent, cell_58, id_1).
diagram_fact(parent, cell_59, id_1).
diagram_fact(parent, cell_6, id_1).
diagram_fact(parent, cell_60, id_1).
diagram_fact(parent, cell_61, id_1).
diagram_fact(parent, cell_62, id_1).
diagram_fact(parent, cell_63, id_1).
diagram_fact(parent, cell_64, id_1).
diagram_fact(parent, cell_7, id_1).
diagram_fact(parent, cell_8, id_1).
diagram_fact(parent, cell_9, id_1).
diagram_fact(relative, cell_12, 1).
diagram_fact(relative, cell_13, 1).
diagram_fact(relative, cell_20, 1).
diagram_fact(relative, cell_23, 1).
diagram_fact(relative, cell_25, 1).
diagram_fact(relative, cell_27, 1).
diagram_fact(relative, cell_32, 1).
diagram_fact(relative, cell_37, 1).
diagram_fact(relative, cell_42, 1).
diagram_fact(relative, cell_53, 1).
diagram_fact(relative, cell_56, 1).
diagram_fact(relative, cell_9, 1).
diagram_fact(root, root_3, root_3).
diagram_fact(rounded, cell_11, 1).
diagram_fact(rounded, cell_12, 0).
diagram_fact(rounded, cell_13, 0).
diagram_fact(rounded, cell_15, 1).
diagram_fact(rounded, cell_19, 1).
diagram_fact(rounded, cell_20, 0).
diagram_fact(rounded, cell_23, 0).
diagram_fact(rounded, cell_25, 0).
diagram_fact(rounded, cell_27, 0).
diagram_fact(rounded, cell_29, 0).
diagram_fact(rounded, cell_30, 0).
diagram_fact(rounded, cell_31, 1).
diagram_fact(rounded, cell_32, 0).
diagram_fact(rounded, cell_35, 0).
diagram_fact(rounded, cell_36, 1).
diagram_fact(rounded, cell_37, 0).
diagram_fact(rounded, cell_40, 0).
diagram_fact(rounded, cell_41, 1).
diagram_fact(rounded, cell_42, 0).
diagram_fact(rounded, cell_45, 0).
diagram_fact(rounded, cell_47, 1).
diagram_fact(rounded, cell_50, 0).
diagram_fact(rounded, cell_52, 1).
diagram_fact(rounded, cell_53, 0).
diagram_fact(rounded, cell_56, 0).
diagram_fact(rounded, cell_58, 1).
diagram_fact(rounded, cell_6, 1).
diagram_fact(rounded, cell_61, 0).
diagram_fact(rounded, cell_64, 0).
diagram_fact(rounded, cell_7, 1).
diagram_fact(rounded, cell_9, 0).
diagram_fact(source, cell_12, id_TovHJiwwyZonmQ_bTznv__15).
diagram_fact(source, cell_13, id_TovHJiwwyZonmQ_bTznv__15).
diagram_fact(source, cell_20, id_8fRTBHWT1LMxwT7S_JYk__3).
diagram_fact(source, cell_23, id_8fRTBHWT1LMxwT7S_JYk__7).
diagram_fact(source, cell_25, id_8fRTBHWT1LMxwT7S_JYk__8).
diagram_fact(source, cell_27, id_8fRTBHWT1LMxwT7S_JYk__9).
diagram_fact(source, cell_32, lLxG6PJgcpTXuLp3OtVY__24).
diagram_fact(source, cell_37, lLxG6PJgcpTXuLp3OtVY__31).
diagram_fact(source, cell_42, lLxG6PJgcpTXuLp3OtVY__37).
diagram_fact(source, cell_53, lLxG6PJgcpTXuLp3OtVY__53).
diagram_fact(source, cell_56, lLxG6PJgcpTXuLp3OtVY__56).
diagram_fact(source, cell_9, id_TovHJiwwyZonmQ_bTznv__10).
diagram_fact(strokeColor, cell_10, "#82b366").
diagram_fact(strokeColor, cell_11, "#6c8ebf").
diagram_fact(strokeColor, cell_14, "#d6b656").
diagram_fact(strokeColor, cell_15, "#6c8ebf").
diagram_fact(strokeColor, cell_16, "#d6b656").
diagram_fact(strokeColor, cell_17, "#82b366").
diagram_fact(strokeColor, cell_18, "#d6b656").
diagram_fact(strokeColor, cell_19, "#6c8ebf").
diagram_fact(strokeColor, cell_21, "#d6b656").
diagram_fact(strokeColor, cell_22, "#82b366").
diagram_fact(strokeColor, cell_24, "#d6b656").
diagram_fact(strokeColor, cell_26, "#d6b656").
diagram_fact(strokeColor, cell_28, "#d6b656").
diagram_fact(strokeColor, cell_29, "#b85450").
diagram_fact(strokeColor, cell_30, "#b85450").
diagram_fact(strokeColor, cell_31, "#6c8ebf").
diagram_fact(strokeColor, cell_33, "#d6b656").
diagram_fact(strokeColor, cell_34, "#82b366").
diagram_fact(strokeColor, cell_35, "#b85450").
diagram_fact(strokeColor, cell_36, "#6c8ebf").
diagram_fact(strokeColor, cell_38, "#d6b656").
diagram_fact(strokeColor, cell_39, "#82b366").
diagram_fact(strokeColor, cell_40, "#b85450").
diagram_fact(strokeColor, cell_41, "#6c8ebf").
diagram_fact(strokeColor, cell_43, "#d6b656").
diagram_fact(strokeColor, cell_44, "#82b366").
diagram_fact(strokeColor, cell_45, "#b85450").
diagram_fact(strokeColor, cell_46, "#82b366").
diagram_fact(strokeColor, cell_47, "#6c8ebf").
diagram_fact(strokeColor, cell_48, "#d6b656").
diagram_fact(strokeColor, cell_49, "#82b366").
diagram_fact(strokeColor, cell_50, "#b85450").
diagram_fact(strokeColor, cell_51, "#d6b656").
diagram_fact(strokeColor, cell_52, "#6c8ebf").
diagram_fact(strokeColor, cell_54, "#d6b656").
diagram_fact(strokeColor, cell_55, "#82b366").
diagram_fact(strokeColor, cell_57, "#d6b656").
diagram_fact(strokeColor, cell_58, "#6c8ebf").
diagram_fact(strokeColor, cell_59, "#d6b656").
diagram_fact(strokeColor, cell_6, "#666666").
diagram_fact(strokeColor, cell_60, "#82b366").
diagram_fact(strokeColor, cell_61, "#b85450").
diagram_fact(strokeColor, cell_62, "#82b366").
diagram_fact(strokeColor, cell_63, "#82b366").
diagram_fact(strokeColor, cell_64, "#b85450").
diagram_fact(strokeColor, cell_7, "#666666").
diagram_fact(strokeColor, cell_8, "#d6b656").
diagram_fact(synonym, cell_10, id_TovHJiwwyZonmQ_bTznv__10).
diagram_fact(synonym, cell_11, id_TovHJiwwyZonmQ_bTznv__13).
diagram_fact(synonym, cell_12, lLxG6PJgcpTXuLp3OtVY__76).
diagram_fact(synonym, cell_13, lLxG6PJgcpTXuLp3OtVY__77).
diagram_fact(synonym, cell_14, id_TovHJiwwyZonmQ_bTznv__15).
diagram_fact(synonym, cell_15, id_TovHJiwwyZonmQ_bTznv__16).
diagram_fact(synonym, cell_16, id_TovHJiwwyZonmQ_bTznv__18).
diagram_fact(synonym, cell_17, id_TovHJiwwyZonmQ_bTznv__21).
diagram_fact(synonym, cell_18, id_TovHJiwwyZonmQ_bTznv__22).
diagram_fact(synonym, cell_19, id_8fRTBHWT1LMxwT7S_JYk__1).
diagram_fact(synonym, cell_20, id_8fRTBHWT1LMxwT7S_JYk__10).
diagram_fact(synonym, cell_21, id_8fRTBHWT1LMxwT7S_JYk__3).
diagram_fact(synonym, cell_22, id_8fRTBHWT1LMxwT7S_JYk__4).
diagram_fact(synonym, cell_23, id_8fRTBHWT1LMxwT7S_JYk__11).
diagram_fact(synonym, cell_24, id_8fRTBHWT1LMxwT7S_JYk__7).
diagram_fact(synonym, cell_25, id_SeB8fdTa3E1rDPtpntBL__6).
diagram_fact(synonym, cell_26, id_8fRTBHWT1LMxwT7S_JYk__8).
diagram_fact(synonym, cell_27, id_SeB8fdTa3E1rDPtpntBL__5).
diagram_fact(synonym, cell_28, id_8fRTBHWT1LMxwT7S_JYk__9).
diagram_fact(synonym, cell_29, d2PD9pr8LVU__TdM__kRBD__1).
diagram_fact(synonym, cell_30, d2PD9pr8LVU__TdM__kRBD__3).
diagram_fact(synonym, cell_31, lLxG6PJgcpTXuLp3OtVY__23).
diagram_fact(synonym, cell_32, lLxG6PJgcpTXuLp3OtVY__57).
diagram_fact(synonym, cell_33, lLxG6PJgcpTXuLp3OtVY__24).
diagram_fact(synonym, cell_34, lLxG6PJgcpTXuLp3OtVY__25).
diagram_fact(synonym, cell_35, lLxG6PJgcpTXuLp3OtVY__26).
diagram_fact(synonym, cell_36, lLxG6PJgcpTXuLp3OtVY__30).
diagram_fact(synonym, cell_37, lLxG6PJgcpTXuLp3OtVY__75).
diagram_fact(synonym, cell_38, lLxG6PJgcpTXuLp3OtVY__31).
diagram_fact(synonym, cell_39, lLxG6PJgcpTXuLp3OtVY__32).
diagram_fact(synonym, cell_4, id_0).
diagram_fact(synonym, cell_40, lLxG6PJgcpTXuLp3OtVY__33).
diagram_fact(synonym, cell_41, lLxG6PJgcpTXuLp3OtVY__36).
diagram_fact(synonym, cell_42, lLxG6PJgcpTXuLp3OtVY__73).
diagram_fact(synonym, cell_43, lLxG6PJgcpTXuLp3OtVY__37).
diagram_fact(synonym, cell_44, lLxG6PJgcpTXuLp3OtVY__38).
diagram_fact(synonym, cell_45, lLxG6PJgcpTXuLp3OtVY__39).
diagram_fact(synonym, cell_46, lLxG6PJgcpTXuLp3OtVY__40).
diagram_fact(synonym, cell_47, lLxG6PJgcpTXuLp3OtVY__43).
diagram_fact(synonym, cell_48, lLxG6PJgcpTXuLp3OtVY__44).
diagram_fact(synonym, cell_49, lLxG6PJgcpTXuLp3OtVY__45).
diagram_fact(synonym, cell_5, id_1).
diagram_fact(synonym, cell_50, lLxG6PJgcpTXuLp3OtVY__46).
diagram_fact(synonym, cell_51, lLxG6PJgcpTXuLp3OtVY__48).
diagram_fact(synonym, cell_52, lLxG6PJgcpTXuLp3OtVY__52).
diagram_fact(synonym, cell_53, lLxG6PJgcpTXuLp3OtVY__74).
diagram_fact(synonym, cell_54, lLxG6PJgcpTXuLp3OtVY__53).
diagram_fact(synonym, cell_55, lLxG6PJgcpTXuLp3OtVY__54).
diagram_fact(synonym, cell_56, lLxG6PJgcpTXuLp3OtVY__59).
diagram_fact(synonym, cell_57, lLxG6PJgcpTXuLp3OtVY__56).
diagram_fact(synonym, cell_58, lLxG6PJgcpTXuLp3OtVY__60).
diagram_fact(synonym, cell_59, lLxG6PJgcpTXuLp3OtVY__61).
diagram_fact(synonym, cell_6, id_TovHJiwwyZonmQ_bTznv__1).
diagram_fact(synonym, cell_60, lLxG6PJgcpTXuLp3OtVY__62).
diagram_fact(synonym, cell_61, lLxG6PJgcpTXuLp3OtVY__63).
diagram_fact(synonym, cell_62, lLxG6PJgcpTXuLp3OtVY__65).
diagram_fact(synonym, cell_63, lLxG6PJgcpTXuLp3OtVY__66).
diagram_fact(synonym, cell_64, lLxG6PJgcpTXuLp3OtVY__72).
diagram_fact(synonym, cell_7, id_TovHJiwwyZonmQ_bTznv__2).
diagram_fact(synonym, cell_8, id_TovHJiwwyZonmQ_bTznv__7).
diagram_fact(synonym, cell_9, id_8fRTBHWT1LMxwT7S_JYk__12).
diagram_fact(target, cell_12, lLxG6PJgcpTXuLp3OtVY__25).
diagram_fact(target, cell_13, lLxG6PJgcpTXuLp3OtVY__32).
diagram_fact(target, cell_20, id_TovHJiwwyZonmQ_bTznv__7).
diagram_fact(target, cell_23, id_TovHJiwwyZonmQ_bTznv__7).
diagram_fact(target, cell_25, id_TovHJiwwyZonmQ_bTznv__7).
diagram_fact(target, cell_27, id_TovHJiwwyZonmQ_bTznv__7).
diagram_fact(target, cell_32, lLxG6PJgcpTXuLp3OtVY__54).
diagram_fact(target, cell_37, id_TovHJiwwyZonmQ_bTznv__22).
diagram_fact(target, cell_42, id_TovHJiwwyZonmQ_bTznv__22).
diagram_fact(target, cell_53, id_TovHJiwwyZonmQ_bTznv__22).
diagram_fact(target, cell_56, lLxG6PJgcpTXuLp3OtVY__38).
diagram_fact(target, cell_9, id_8fRTBHWT1LMxwT7S_JYk__4).
diagram_fact(value, cell_10, "phrase").
diagram_fact(value, cell_11, "HTML Button").
diagram_fact(value, cell_14, "click").
diagram_fact(value, cell_15, "Input Text").
diagram_fact(value, cell_16, "text").
diagram_fact(value, cell_17, "go").
diagram_fact(value, cell_18, "food order").
diagram_fact(value, cell_19, "Phrase Parser").
diagram_fact(value, cell_21, "order no choices").
diagram_fact(value, cell_22, "phrase").
diagram_fact(value, cell_24, "order with choices").
diagram_fact(value, cell_26, "parse error").
diagram_fact(value, cell_28, "hook error").
diagram_fact(value, cell_29, "me.send (&quot;click&quot;, true);").
diagram_fact(value, cell_30, "&lt;div&gt;console.log ('input 1');&lt;/div&gt;&lt;div&gt;&amp;nbsp; &amp;nbsp; me.send (&quot;text&quot;, getText ('src'));&lt;/div&gt;").
diagram_fact(value, cell_31, "junk1").
diagram_fact(value, cell_33, "text").
diagram_fact(value, cell_34, "go").
diagram_fact(value, cell_35, "&lt;div&gt;console.log ('junk1');&lt;/div&gt;&lt;div&gt;&amp;nbsp; &amp;nbsp; var data = {item:&quot;hello&quot;, extras: &quot;h extra&quot;, condiments: &quot;h condiments&quot;};&lt;br&gt;&lt;/div&gt;&lt;div&gt;console.log (data);&lt;/div&gt;&amp;nbsp; &amp;nbsp; me.send (&quot;text&quot;, data);").
diagram_fact(value, cell_36, "junk2").
diagram_fact(value, cell_38, "text").
diagram_fact(value, cell_39, "go").
diagram_fact(value, cell_40, "&lt;div&gt;console.log ('junk2');&lt;/div&gt;&lt;div&gt;&amp;nbsp; &amp;nbsp; me.send (&quot;text&quot;, {item:&quot;goodbye&quot;, extras: &quot;g extra&quot;, condiments: &quot;g condiments&quot;});&lt;/div&gt;").
diagram_fact(value, cell_41, "junk3").
diagram_fact(value, cell_43, "text").
diagram_fact(value, cell_44, "text1").
diagram_fact(value, cell_45, "&lt;div&gt;console.log ('test 3');&lt;/div&gt;&lt;div&gt;var newdata = Object.assign ({}, message.data);&lt;/div&gt;&lt;div&gt;newdata.item = &quot;test3 ... &quot; + message.data.item;&lt;/div&gt;&lt;div&gt;&amp;nbsp; &amp;nbsp; console.log (newdata);&lt;/div&gt;&lt;div&gt;me.send (&quot;text&quot;, newdata);&lt;/div&gt;").
diagram_fact(value, cell_46, "text2").
diagram_fact(value, cell_47, "fanout").
diagram_fact(value, cell_48, "out1").
diagram_fact(value, cell_49, "in").
diagram_fact(value, cell_50, "&lt;div&gt;console.log ('fanout');&lt;/div&gt;&lt;div&gt;&amp;nbsp; &amp;nbsp; me.send (&quot;out1&quot;, message.data);&lt;/div&gt;&lt;div&gt;me.send (&quot;out2&quot;, message.data);&lt;/div&gt;").
diagram_fact(value, cell_51, "out2").
diagram_fact(value, cell_52, "fanout x").
diagram_fact(value, cell_54, "out1").
diagram_fact(value, cell_55, "in").
diagram_fact(value, cell_57, "out2").
diagram_fact(value, cell_58, "fanin").
diagram_fact(value, cell_59, "out").
diagram_fact(value, cell_6, "Test Bench").
diagram_fact(value, cell_60, "in1").
diagram_fact(value, cell_61, "&lt;div&gt;console.log ('fan in');&lt;/div&gt;&lt;div&gt;&amp;nbsp; &amp;nbsp; me.send (&quot;out&quot;, message.data);&lt;/div&gt;").
diagram_fact(value, cell_62, "in2").
diagram_fact(value, cell_63, "in3").
diagram_fact(value, cell_64, "&lt;div&gt;console.log ('xfanout');&lt;/div&gt;&lt;div&gt;&amp;nbsp; &amp;nbsp; me.send (&quot;out1&quot;, message.data);&lt;/div&gt;&lt;div&gt;me.send(&quot;out2&quot;, message.data);&lt;/div&gt;").
diagram_fact(value, cell_7, "Order Taker").
diagram_fact(value, cell_8, "food order").
diagram_fact(vertex, cell_10, 1).
diagram_fact(vertex, cell_11, 1).
diagram_fact(vertex, cell_14, 1).
diagram_fact(vertex, cell_15, 1).
diagram_fact(vertex, cell_16, 1).
diagram_fact(vertex, cell_17, 1).
diagram_fact(vertex, cell_18, 1).
diagram_fact(vertex, cell_19, 1).
diagram_fact(vertex, cell_21, 1).
diagram_fact(vertex, cell_22, 1).
diagram_fact(vertex, cell_24, 1).
diagram_fact(vertex, cell_26, 1).
diagram_fact(vertex, cell_28, 1).
diagram_fact(vertex, cell_29, 1).
diagram_fact(vertex, cell_30, 1).
diagram_fact(vertex, cell_31, 1).
diagram_fact(vertex, cell_33, 1).
diagram_fact(vertex, cell_34, 1).
diagram_fact(vertex, cell_35, 1).
diagram_fact(vertex, cell_36, 1).
diagram_fact(vertex, cell_38, 1).
diagram_fact(vertex, cell_39, 1).
diagram_fact(vertex, cell_40, 1).
diagram_fact(vertex, cell_41, 1).
diagram_fact(vertex, cell_43, 1).
diagram_fact(vertex, cell_44, 1).
diagram_fact(vertex, cell_45, 1).
diagram_fact(vertex, cell_46, 1).
diagram_fact(vertex, cell_47, 1).
diagram_fact(vertex, cell_48, 1).
diagram_fact(vertex, cell_49, 1).
diagram_fact(vertex, cell_50, 1).
diagram_fact(vertex, cell_51, 1).
diagram_fact(vertex, cell_52, 1).
diagram_fact(vertex, cell_54, 1).
diagram_fact(vertex, cell_55, 1).
diagram_fact(vertex, cell_57, 1).
diagram_fact(vertex, cell_58, 1).
diagram_fact(vertex, cell_59, 1).
diagram_fact(vertex, cell_6, 1).
diagram_fact(vertex, cell_60, 1).
diagram_fact(vertex, cell_61, 1).
diagram_fact(vertex, cell_62, 1).
diagram_fact(vertex, cell_63, 1).
diagram_fact(vertex, cell_64, 1).
diagram_fact(vertex, cell_7, 1).
diagram_fact(vertex, cell_8, 1).
diagram_fact(verticalAlign, cell_11, "top").
diagram_fact(verticalAlign, cell_15, "top").
diagram_fact(verticalAlign, cell_19, "top").
diagram_fact(verticalAlign, cell_31, "top").
diagram_fact(verticalAlign, cell_36, "top").
diagram_fact(verticalAlign, cell_41, "top").
diagram_fact(verticalAlign, cell_47, "top").
diagram_fact(verticalAlign, cell_52, "top").
diagram_fact(verticalAlign, cell_58, "top").
diagram_fact(verticalAlign, cell_6, "top").
diagram_fact(verticalAlign, cell_7, "top").
diagram_fact(whiteSpace, cell_10, "wrap").
diagram_fact(whiteSpace, cell_11, "wrap").
diagram_fact(whiteSpace, cell_14, "wrap").
diagram_fact(whiteSpace, cell_15, "wrap").
diagram_fact(whiteSpace, cell_16, "wrap").
diagram_fact(whiteSpace, cell_17, "wrap").
diagram_fact(whiteSpace, cell_18, "wrap").
diagram_fact(whiteSpace, cell_19, "wrap").
diagram_fact(whiteSpace, cell_21, "wrap").
diagram_fact(whiteSpace, cell_22, "wrap").
diagram_fact(whiteSpace, cell_24, "wrap").
diagram_fact(whiteSpace, cell_26, "wrap").
diagram_fact(whiteSpace, cell_28, "wrap").
diagram_fact(whiteSpace, cell_29, "wrap").
diagram_fact(whiteSpace, cell_30, "wrap").
diagram_fact(whiteSpace, cell_31, "wrap").
diagram_fact(whiteSpace, cell_33, "wrap").
diagram_fact(whiteSpace, cell_34, "wrap").
diagram_fact(whiteSpace, cell_35, "wrap").
diagram_fact(whiteSpace, cell_36, "wrap").
diagram_fact(whiteSpace, cell_38, "wrap").
diagram_fact(whiteSpace, cell_39, "wrap").
diagram_fact(whiteSpace, cell_40, "wrap").
diagram_fact(whiteSpace, cell_41, "wrap").
diagram_fact(whiteSpace, cell_43, "wrap").
diagram_fact(whiteSpace, cell_44, "wrap").
diagram_fact(whiteSpace, cell_45, "wrap").
diagram_fact(whiteSpace, cell_46, "wrap").
diagram_fact(whiteSpace, cell_47, "wrap").
diagram_fact(whiteSpace, cell_48, "wrap").
diagram_fact(whiteSpace, cell_49, "wrap").
diagram_fact(whiteSpace, cell_50, "wrap").
diagram_fact(whiteSpace, cell_51, "wrap").
diagram_fact(whiteSpace, cell_52, "wrap").
diagram_fact(whiteSpace, cell_54, "wrap").
diagram_fact(whiteSpace, cell_55, "wrap").
diagram_fact(whiteSpace, cell_57, "wrap").
diagram_fact(whiteSpace, cell_58, "wrap").
diagram_fact(whiteSpace, cell_59, "wrap").
diagram_fact(whiteSpace, cell_6, "wrap").
diagram_fact(whiteSpace, cell_60, "wrap").
diagram_fact(whiteSpace, cell_61, "wrap").
diagram_fact(whiteSpace, cell_62, "wrap").
diagram_fact(whiteSpace, cell_63, "wrap").
diagram_fact(whiteSpace, cell_64, "wrap").
diagram_fact(whiteSpace, cell_7, "wrap").
diagram_fact(whiteSpace, cell_8, "wrap").
diagram_fact(width, cell_10, 40).
diagram_fact(width, cell_11, 190).
diagram_fact(width, cell_14, 40).
diagram_fact(width, cell_15, 380).
diagram_fact(width, cell_16, 40).
diagram_fact(width, cell_17, 40).
diagram_fact(width, cell_18, 40).
diagram_fact(width, cell_19, 120).
diagram_fact(width, cell_21, 40).
diagram_fact(width, cell_22, 40).
diagram_fact(width, cell_24, 40).
diagram_fact(width, cell_26, 40).
diagram_fact(width, cell_28, 40).
diagram_fact(width, cell_29, 140).
diagram_fact(width, cell_30, 270).
diagram_fact(width, cell_31, 380).
diagram_fact(width, cell_33, 40).
diagram_fact(width, cell_34, 40).
diagram_fact(width, cell_35, 270).
diagram_fact(width, cell_36, 380).
diagram_fact(width, cell_38, 40).
diagram_fact(width, cell_39, 40).
diagram_fact(width, cell_40, 270).
diagram_fact(width, cell_41, 380).
diagram_fact(width, cell_43, 40).
diagram_fact(width, cell_44, 40).
diagram_fact(width, cell_45, 270).
diagram_fact(width, cell_46, 40).
diagram_fact(width, cell_47, 380).
diagram_fact(width, cell_48, 40).
diagram_fact(width, cell_49, 40).
diagram_fact(width, cell_50, 270).
diagram_fact(width, cell_51, 40).
diagram_fact(width, cell_52, 380).
diagram_fact(width, cell_54, 40).
diagram_fact(width, cell_55, 40).
diagram_fact(width, cell_57, 40).
diagram_fact(width, cell_58, 380).
diagram_fact(width, cell_59, 40).
diagram_fact(width, cell_6, 2110).
diagram_fact(width, cell_60, 40).
diagram_fact(width, cell_61, 270).
diagram_fact(width, cell_62, 40).
diagram_fact(width, cell_63, 40).
diagram_fact(width, cell_64, 270).
diagram_fact(width, cell_7, 330).
diagram_fact(width, cell_8, 40).
diagram_fact(x, cell_10, 810).
diagram_fact(x, cell_11, 60).
diagram_fact(x, cell_14, 230).
diagram_fact(x, cell_15, 330).
diagram_fact(x, cell_16, 690).
diagram_fact(x, cell_17, 310).
diagram_fact(x, cell_18, 2130).
diagram_fact(x, cell_19, 910).
diagram_fact(x, cell_21, 1010).
diagram_fact(x, cell_22, 890).
diagram_fact(x, cell_24, 1010).
diagram_fact(x, cell_26, 920).
diagram_fact(x, cell_28, 970).
diagram_fact(x, cell_29, 80).
diagram_fact(x, cell_30, 385).
diagram_fact(x, cell_31, 770).
diagram_fact(x, cell_33, 1130).
diagram_fact(x, cell_34, 750).
diagram_fact(x, cell_35, 825).
diagram_fact(x, cell_36, 780).
diagram_fact(x, cell_38, 1140).
diagram_fact(x, cell_39, 760).
diagram_fact(x, cell_40, 835).
diagram_fact(x, cell_41, 800).
diagram_fact(x, cell_43, 1160).
diagram_fact(x, cell_44, 780).
diagram_fact(x, cell_45, 855).
diagram_fact(x, cell_46, 780).
diagram_fact(x, cell_47, 280).
diagram_fact(x, cell_48, 640).
diagram_fact(x, cell_49, 260).
diagram_fact(x, cell_50, 335).
diagram_fact(x, cell_51, 640).
diagram_fact(x, cell_52, 310).
diagram_fact(x, cell_54, 670).
diagram_fact(x, cell_55, 290).
diagram_fact(x, cell_57, 670).
diagram_fact(x, cell_58, 1600).
diagram_fact(x, cell_59, 1960).
diagram_fact(x, cell_6, 40).
diagram_fact(x, cell_60, 1580).
diagram_fact(x, cell_61, 1655).
diagram_fact(x, cell_62, 1580).
diagram_fact(x, cell_63, 1580).
diagram_fact(x, cell_64, 365).
diagram_fact(x, cell_7, 830).
diagram_fact(x, cell_8, 1140).
diagram_fact(y, cell_10, -650).
diagram_fact(y, cell_11, -675).
diagram_fact(y, cell_14, -635).
diagram_fact(y, cell_15, -670).
diagram_fact(y, cell_16, -625).
diagram_fact(y, cell_17, -635).
diagram_fact(y, cell_18, -675).
diagram_fact(y, cell_19, -700).
diagram_fact(y, cell_21, -675).
diagram_fact(y, cell_22, -650).
diagram_fact(y, cell_24, -625).
diagram_fact(y, cell_26, -570).
diagram_fact(y, cell_28, -570).
diagram_fact(y, cell_29, -635).
diagram_fact(y, cell_30, -635).
diagram_fact(y, cell_31, -360).
diagram_fact(y, cell_33, -315).
diagram_fact(y, cell_34, -325).
diagram_fact(y, cell_35, -325).
diagram_fact(y, cell_36, -190).
diagram_fact(y, cell_38, -145).
diagram_fact(y, cell_39, -155).
diagram_fact(y, cell_40, -155).
diagram_fact(y, cell_41, 80).
diagram_fact(y, cell_43, 125).
diagram_fact(y, cell_44, 115).
diagram_fact(y, cell_45, 115).
diagram_fact(y, cell_46, 165).
diagram_fact(y, cell_47, -335).
diagram_fact(y, cell_48, -290).
diagram_fact(y, cell_49, -300).
diagram_fact(y, cell_50, -275).
diagram_fact(y, cell_51, -235).
diagram_fact(y, cell_52, 10).
diagram_fact(y, cell_54, 55).
diagram_fact(y, cell_55, 45).
diagram_fact(y, cell_57, 110).
diagram_fact(y, cell_58, -375).
diagram_fact(y, cell_59, -280).
diagram_fact(y, cell_6, -780).
diagram_fact(y, cell_60, -340).
diagram_fact(y, cell_61, -290).
diagram_fact(y, cell_62, -280).
diagram_fact(y, cell_63, -225).
diagram_fact(y, cell_64, 55).
diagram_fact(y, cell_7, -735).
diagram_fact(y, cell_8, -650).
